# Generated by Django 4.1.1 on 2022-09-08 03:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roadsegment',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Long_start', models.FloatField()),
                ('Lat_start', models.FloatField()),
                ('Long_end', models.FloatField()),
                ('Lat_end', models.FloatField()),
                ('Length', models.FloatField()),
                ('Speed', models.FloatField()),
                ('Intensity', models.CharField(choices=[('2', '2'), ('1', '1'), ('0', '0')], default='99', max_length=1)),
                ('Characterization', models.CharField(choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], default='default', max_length=8)),
                ('Segment_start', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('Segment_end', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('Segment', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
